name: Pathecho CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_TAG: v1.0.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:        
  dockerhub:
    name: Docker
    runs-on: ubuntu-22.04

    steps:
    - name: Show docker version
      run: docker version

    - name: Checkout sources
      uses: actions/checkout@v3
 
    - name: Build pathecho container image locally
      run: docker build -t email4tong/pathecho:${{ env.IMAGE_TAG }} .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_KEY }}

    - name: Build and push images
      run: |
        docker buildx build --push \
          --tag email4tong/pathecho:${{env.IMAGE_TAG}} \
          --platform linux/amd64,linux/arm64 .

    - name: Build and push images with latest tag
      run: |
        docker buildx build --push \
          --tag email4tong/pathecho:latest \
          --platform linux/amd64,linux/arm64 .
    