name: Pathecho CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_TAG: v0.1.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:        
  dockerhub:
    name: Docker
    runs-on: ubuntu-22.04

    steps:
    - name: Show docker version
      run: docker version

    - name: Checkout sources
      uses: actions/checkout@v3
 
    - name: set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_KEY }}

    - name: build and push images
      run: |
        docker buildx build --push \
          --tag email4tong/pathecho:${{env.IMAGE_TAG}} \
          --platform linux/amd64,linux/arm64 .
